### ISSUE TITLE
Document how to add a new Alignment/Guidetree/Eval module

### ISSUE THREAD

**Issue by lrauschning** [nf-core/multiplesequencealign#102]
### Description of feature

As we talked about, there should be something like a Checklist or Step-by-Step Tutorial on this in the documentation.

**Comment by lrauschning** [comment]
Set up a branch for this and some skeleton initial documentation: https://github.com/lrauschning/multiplesequencealign/tree/doc

**Comment by luisas** [comment]
Closed by #125
