### ISSUE TITLE
INPUT VALIDATION: what to do with unsupported and harmful flags of aligners modules?

### ISSUE THREAD

**Issue by alessiovignoli** [nf-core/multiplesequencealign#74]
### Description of feature

There are some flags that the user is able to specify from the samplesheet.csv that might be annoying for the pipeline (unsupported).  
Some other flags do even brack the pipeline in itself, for example we would want the aligners not to compress the output as of today. So if the user passes the flag to do so it is likely going to breack the pipeline.

The question is the following. How to deal with this harmfull flags?.

This should be where the ideas are brainstormed.

**Comment by luisas** [comment]
This should be done in the validation of the toolsheet at the beginning of the pipeline. 

 - Add minimal flags as default if not given (example: 3Dcoffee should not be allowed to run without a structural method, same as regressive without the -reg flag) 
 - Reference in documentation where one can find the optional extra flags. 
 
 SO: we need to make sure the minimal ones are always present, no need to check for optional flags, those are responsibility of the user but describe well in documentation.

**Comment by luisas** [comment]
I made  a custom validation in the WorkflowMultiplesequencealign.groovy file. 

there is an open issue in nf-validation, when they enable it, we can update it. 

For the moment, this is it with the input validation i'd say. 

==> Closed by #93
