### ISSUE TITLE
Add TCS as evaluation metric

### ISSUE THREAD

**Issue by luisas** [nf-core/multiplesequencealign#90]
### Description of feature

Add TCS as evaluation metric

**Comment by luisas** [comment]
https://github.com/luisas/nf_structural_regression/blob/master/modules/evaluate_alignment.nf

TCS from here

**Comment by luisas** [comment]
also, make it optionale to pass library (as of TCS_LIB)

**Comment by alessiovignoli** [comment]
It has to have the following features:

- handle compressed input, if at beginnin and null container )from IRMSD)
- output style either csv like aln_compare or what it is and then parse it.
-  skippable.
-  LIB as optional input.

**Comment by alessiovignoli** [comment]
The module itself has the lib file as optional. But the pipeline for now does not allow for the lib file to be passed to the module. Thing for a future Issue.

**Comment by luisas** [comment]
Closed by #115
